services:
  - type: web
    name: fake-store-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: fake-store-super-secret-key-2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_ENV
        value: production
